### PR TITLE
incorporate multiplier of futures

### PR DESCRIPTION
**Pull request by gansaihua**
Follow discussion #448.

### CODE REVIEW

**Comment by tthkp** [comment]
Hello, can i check whether this pull request has been incorporated yet? 
Similar, I would like to backtest for future, and a multiplier would help to do so, thanks.

**Comment by fortesantonio** [comment]
wouldnt it be easier to make a pip cost function to account for decimal location and contract size to determine pnl of the position ?

**Comment by fortesantonio** [comment]
> 

Pip Value = (Stop Loss Length in Pips) * (Pip Cost)
Position Size or Lots = (% of Account Risk) / (Pip Cost)
Limit Profit in Pips= (Stop Loss Length in Pips) * (Reward to Risk Multiple)

Stop Loss $ Value = (Pip Cost) * (Lots) * (Stop Loss Length in Pips)
Limit Profit $ Value = (Pip Cost) * (Lots) * (Limit Profit Length in Pips)

Applied Leverage = (Live Asset Price) * (Position Size or Lots) / (Account Balance)

https://www.fxcm.com/markets/insights/how-is-the-value-of-a-pip-determined/
https://www.dailyfx.com/education/beginner/what-is-a-pip.html

**Comment by kernc** [comment]
Closing in favor of simplicity, https://github.com/kernc/backtesting.py/discussions/448#discussioncomment-4315296. Someone check the math there, please. 😅

**Pull request closed without merging**
