### PR TITLE
[WIP] Feature: Support for multiple Instruments.

### PR DESCRIPTION
**Pull request by AgarwalPragy**
An incomplete attempt to add multiple-instrument backtest, which is mentioned in https://github.com/kernc/backtesting.py/issues/20 and https://github.com/kernc/backtesting.py/discussions/418

Aim: full backwards compatibility

How?
class `Backtest` will accept `data` as either a `pd.DataFrame` or a dictionary containing instrument names (`str`) and corresponding instrument data (`pd.DataFrame`). class `_Data` will follow suit.

class `_Data` will get a property `is_single_instrument` which tells us if the single-instrument-mode is enabled.

Internally, all classes will assume that the data is in multi-instrument mode. However, the signatures for methods in the existing API will be extended to return dictionaries instead of single-value if the multi-instrument mode is enabled.

### CODE REVIEW

**Comment by AgarwalPragy** [comment]
A parallel effort for the same feature by Robert: https://github.com/kernc/backtesting.py/pull/639

**Comment by AgarwalPragy** [comment]
@kernc would you be willing to accept this PR? If you have a better way in mind, please let me know :)

**Comment by luketych** [comment]
How is this coming along?

**Comment by luketych** [comment]
How is this coming along? @tumma72 @AgarwalPragy

**Comment by tumma72** [comment]
To be honest, I gave up trying to bend the beast, and decided to create my own bot, which support backtesting, paper-trading and live-trading using the CCXT Library which works quite well with a number of Exchanges, and it is well maintained.

**Comment by dodid** [comment]
I made an attempt to support multiple instruments based on kernc's excellent work. See https://github.com/dodid/minitrade The support is quite basic and feedback is welcome on how to make it more useful.

**Pull request closed without merging**
